Day 8- Q2: Leaf at same level #260 cpp code added.
SnowScriptWinterOfCode/LeetCode_Q pull request #265
Opened 2024-01-04 13:39 UTC by Akansha77

Day 8- Q2: Leaf at same level #260 cpp code added by Akansha77

2024-01-04 16:09 UTC, bh-g commented
The question has already been added to the repo, add your solution in the same folder by creating a file Akansha--C.md

2024-01-04 16:31 UTC, Akansha77 commented
dii what is the name of the folder in the repo ?

2024-01-04 18:38 UTC, bh-g requested changes

2024-01-04 18:38 UTC, bh-g commented on Others/Day_8-Q2_Leaf_at_the_same_level/question.md
no need to add question

2024-01-04 18:38 UTC, bh-g commented on Others/Day_8-Q2_Leaf_at_the_same_level/Akansha--C.cpp
Hey, you've named the file correctly:)
However, you don't need to make a new folder, there already exists a folder for this question, pls add the file here-
Day-8/q2: All leaf nodes at same level/

2024-01-04 19:24 UTC, Akansha77 commented
dii changes done

2024-01-05 10:51 UTC, bh-g commented
Same as #282

2024-01-05 10:51 UTC, closed without merging