Find Smallest Letter Greater Than Target | issue #17
SnowScriptWinterOfCode/LeetCode_Q pull request #30
Opened 2023-12-29 15:19 UTC by namita0210

- Written the code in java in "others folder"
- Updated question.md --> added problem statement, solution steps , name of java file that consists of the code.
 
<img width="957" alt="image" src="https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/46557775/ff8bfef0-593e-4a2f-af43-46b14a6f5a45">

Please merge my PR :)

2023-12-29 15:45 UTC, bh-g requested changes

2023-12-29 15:45 UTC, bh-g commented on Others/Name Of Question (template)/q1.java
Make a new Folder in Others with the name: Find Smallest Letter Greater Than Target.
Inside that make two new files question.md and solution.java and add your question and solution there.

2023-12-29 17:17 UTC, namita0210 commented on Others/Name Of Question (template)/q1.java
- Made the changes in the  forked repo
- committed the changes
**Question :** PR was already created -  I made the suggested changes now . Do I need to create PR again?

2023-12-29 19:18 UTC, bh-g requested changes

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/question.md
Move the folder named Find Smallest Letter Greater Than Target inside Others and not inside the template, look at word search for reference.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/question.md
> +###Write the question here!
Remove this line.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/question.md
> +  <b color="blue"> Q1. Find smallest letter greater than target</b><br>
Remove 'Q1'.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/question.md
> +
Delete this.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/question.md
Add examples in the question.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/solution.java
> +
Delete this.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/solution.java
> +}
Not needed, delete this.

2023-12-29 19:18 UTC, bh-g commented on Others/Name Of Question (template)/Find Smallest Letter Greater Than Target/solution.java
> +    }
Re-indent this part after removing rest of the code.

2023-12-30 17:46 UTC, namita0210 commented
### Issue #17  Fixed

- Solution snapshot

- <img width="620" alt="image" src="https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/46557775/557f9069-7f9a-42e2-95d2-63dc589050f7">

- Question snapshot

- <img width="915" alt="image" src="https://github.com/SnowScriptWinterOfCode/LeetCode_Q/assets/46557775/9a1235c0-afa7-47d9-b256-4b933876355a">

2023-12-31 07:45 UTC, namita0210 commented
> ### Issue #17 Fixed
> * Solution snapshot
> * <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/46557775/293473048-557f9069-7f9a-42e2-95d2-63dc589050f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDg5MzksIm5iZiI6MTcwNDAwODYzOSwicGF0aCI6Ii80NjU1Nzc3NS8yOTM0NzMwNDgtNTU3ZjkwNjktN2Y5YS00MmUyLTk1ZDItNjNkYzU4OTA1MGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTdjNTEzMjY2MzhmZmQ2OGEzNzdmMGFlOWE2YjQ3MmE1MzhkMDkwNGRhZDc3YTRkMDY5ZmRiMjM1MjNhNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TnoW6afktezgD7I5Tv5sUJrcj_5rKKF5dIqJ_Tk_0Bs">
> * Question snapshot
> * <img alt="image" width="915" src="https://private-user-images.githubusercontent.com/46557775/293473089-9a1235c0-afa7-47d9-b256-4b933876355a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDg5MzksIm5iZiI6MTcwNDAwODYzOSwicGF0aCI6Ii80NjU1Nzc3NS8yOTM0NzMwODktOWExMjM1YzAtYWZhNy00N2Q5LWIyNTYtNGI5MzM4NzYzNTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlYjdiYzZhMGI5NDE0OTVhY2ZkZjQyMjU3YjFlY2E1Mzc1MTViY2NjMDc4MjliMmJhZjdiNTliMmI2YTFmMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VD5aJP16oVvjrdoDMYZ4vmwlY6pwexhukqlnCKk4qYU">

Hi @bh-g  All the changes have been made - Can you please merge this PR ?

2023-12-31 16:17 UTC, merged